### PR TITLE
use pkg_resources

### PR DESCRIPTION
**Pull request by ameisner**
trying to respond to issue #4 

@dstndstn @moustakas  @schlafly 

does this do what we want?

### CODE REVIEW

**Comment by schlafly** [comment]
Looks fine to me.  For what it's worth, I don't think you need to specify os and warnings as dependencies; these are part of the python standard library, so are included in the ~implied "python" dependency.

**Comment by ameisner** [comment]
Thanks. I just removed 'os' and 'warnings' from the README dependency list.

**Comment by ameisner** [comment]
Assuming this gets merged, should I create a tag called "dr9c" or something like that for this updated version of unwise_psf?

**Comment by dstndstn** [comment]
Looks good to me!  Go ahead and merge, as far as I'm concerned!  And sure, if you wouldn't mind tagging a new version, that would be great.  Maybe "dr9.0"?

**Comment by ameisner** [comment]
I'll create a corresponding tag shortly...

**Pull request merged**
